name: Build and publish package
on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v3
        with:
          poetry-version: "latest"

      - name: Build and publish to PYPI.
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.ARACHNID_SHIELD_SDK_PYPI_TOKEN }}
        run: |
            poetry publish --build --repository pypi
      - name: Save built package.
        uses: actions/upload-artifact@v2
        with:
            name: release-${{ github.event.release.id }}
            path: dist/
